### ISSUE TITLE
PRISM merged resources not available at design time

### ISSUE THREAD

**Issue by OzBob** [mvegaca/MyDotNetCoreWpfApp#1]
If open the PRISM.sln, restore Nuget packages, build, debug, stop and then design the MainPage.xaml I get the Error:

XDG0062	The resource "PageTitleStyle" could not be resolved.	MyDotNetCoreWpfAppPrism	MainPage.xaml	18

It also happens if I generate my own WTS PRISM based app.

BlankPage.xaml does not show the same errors, but F12 still does not work ,eg. MediumLeftMargin.

If I open the MVVMLight solution (etc. as above), and view the MainPage.xaml ,there are no styles Errors. I can even F12 on a resource and it navigates.

**Comment by mvegaca** [comment]
Nice catch @OzBob I've just fixed in the mockup and it'll be fixed on generated code soon.
